spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/DiaHelper
    username: postgres
    driver-class-name: org.postgresql.Driver
    password: qwerty007
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true